// ═══════════════════════════════════════════════════════════════════
// HERMES Scanner - Hisse Evreni
// FMP API market cap verilerine gore siniflandirilmis
// MEGA: 70 | LARGE: 954 | MID: 875 | SMALL: 836 | MICRO: 42 = 2777 toplam
// ═══════════════════════════════════════════════════════════════════

import { Segment } from './types'

export const SEGMENTS: Record<Exclude<Segment, 'ALL'>, string[]> = {
  MEGA: [
    'SONY','NTDOY','NVDA','MSFT','AAPL','GOOG','GOOGL','AMZN','META','AVGO',
    'NVO','TSLA','JPM','WMT','LLY','V','ORCL','MA','NFLX','XOM',
    'JNJ','PLTR','ABBV','COST','BAC','HD','GE','UNH','CVX','CSCO',
    'TMUS','WFC','IBM','AMD','MU','MS','CRM','GS','AZN','ABT',
    'RTX','CAT','LIN','MRK','MCD','DIS','T','ASML','AXP','BABA',
    'GEV','HESAY','HSBC','KO','LRLCY','LVMUY','MUFG','NSRGY','NVS','PEP',
    'PG','PM','RHHBY','RY','SAP','SHEL','SIEGY','TCEHY','TM','TSM',
  ],
  LARGE: [
    'SHOP','INTU','C','AMAT','ANET','VZ','QCOM','BLK','TMO','BKNG',
    'SCHW','TXN','LRCX','BA','INTC','ISRG','ACN','TJX','NEE','AMGN',
    'PANW','SPGI','ETN','PGR','BSX','KLAC','SYK','UNP','GILD','CRWD',
    'PFE','HON','ADBE','LOW','DHR','HOOD','DE','SPOT','MDT','WELL',
    'MELI','COP','CMCSA','ADI','LMT','CB','DELL','PLD','SO','HCA',
    'VRTX','SNY','SBUX','CME','NKE','RBLX','ICE','DUK','PH','CVS',
    'CDNS','TT','NEM','SNOW','BMY','ORLY','AMT','GD','COIN','GSK',
    'RCL','NOC','MCO','SHW','MMM','MRVL','PNC','HWM','ECL','WMB',
    'AON','EQIX','CI','TDG','ITW','ABNB','USB','EMR','NET','UPS',
    'MAR','FISV','JCI','EPD','NSC','FDX','CSX','PYPL','FTNT','WDAY',
    'KMI','TRV','HLT','SPG','APD','EOG','AEP','ALNY','AFL','TFC',
    'DLR','SRE','MPC','REGN','AZO','CMI','NXPI','FCX','ALL','FAST',
    'LHX','O','PSX','MET','STX','VLO','ZS','CVNA','CMG','PCAR',
    'LNG','ROST','IDXX','NDAQ','CARR','SLB','EA','DDOG','WBD','BKR',
    'TTWO','VEEV','AMP','OXY','OKE','GWW','EXC','EW','WDC','WCN',
    'AIG','MSCI','AME','YUM','TGT','TEAM','CCI','FANG','EBAY','A',
    'ETR','ROK','NOW','LYV','TRGP','WEC','CHTR','DAL','PRU','ED',
    'OTIS','FIS','CCL','PCG','IR','CTSH','HPE','PSTG','NUE','KEYS',
    'UAL','VTR','HUM','SOFI','DTE','MDB','SMCI','AEE','FOXA','AVB',
    'FE','ES','EXPE','ZM','DXCM','HPQ','CBOE','FOX','MTD','EQR',
    'PPL','TTD','HUBS','IP','CYBR','PTC','AFRM','PPG','FSLR','TPR',
    'WSM','ULTA','DOV','TROW','DVN','CMS','PINS','PODD','DG','TOST',
    'TER','EIX','NTAP','HAL','QSR','SBAC','BIIB','STLD','DLTR','BNTX',
    'DRI','ON','GPN','BE','IT','PKG','LULU','ZBH','RL','GDDY',
    'LII','FFIV','IONQ','INVH','THC','BURL','CNC','LUV','WAT','BBY',
    'GEN','U','INCY','BSY','MNDY','DOW','OKTA','LYB','CHRW','DPZ',
    'OMC','TXT','ZBRA','TWLO','XPO','DECK','DOCU','MAS','KIM','RS',
    'ROKU','DUOL','ILMN','ARE','NBIX','REG','BALL','DD','CHWY','H',
    'JBHT','UDR','SNAP','AVY','MANH','AMH','BEN','IONS','BXP','PAYC',
    'W','CPT','POOL','HII','SWK','NCLH','TXRH','AKAM','HAS','EXEL',
    'BMRN','IVZ','FDS','MOH','MRNA','ABBNY','ABEV','ACCYY','ACGL','ACM',
    'ADDYY','ADM','ADP','ADRNY','ADSK','ADYEY','AEG','AEM','AER','AES',
    'AETUF','AFG','AFLYY','AGI','AIQUY','AIT','AIZ','AJG','AKZOY','ALAB',
    'ALC','ALIZY','ALLE','ALLY','AMCR','AMKBY','AMKR','AMX','AOS','APG',
    'APH','APO','APP','APTV','AR','ARCC','ARES','ARGX','ARM','ARMK',
    'AS','ASAZY','ASMIY','ASND','ASR','ASTS','ASX','ATI','ATLKY','ATO',
    'AU','AVAV','AWK','AXAHY','AXIA','AXON','B','BAESY','BAH','BAIDF',
    'BAM','BAP','BASFY','BAX','BAYRY','BBD','BBIO','BBSEY','BBVA','BCE',
    'BCH','BCS','BDORY','BDRBF','BDX','BEKE','BG','BHP','BIDU','BILI',
    'BIP','BJ','BK','BLD','BLDR','BMO','BN','BNPQY','BNS','BOLSY',
    'BP','BRO','BSBR','BTI','BUD','BVVBY','BWA','BWXT','BX','BYDDF',
    'BYDDY','CACI','CAH','CASY','CBRE','CCEP','CCHGY','CCJ','CCK','CDE',
    'CDW','CEG','CELH','CF','CFG','CFRUY','CG','CHD','CHKP','CIB',
    'CIEN','CINF','CL','CLH','CLNXF','CLPBY','CLS','CLX','CM','CMA',
    'CNA','CNH','CNI','CNM','CNP','CNQ','CODYY','COF','COHR','COO',
    'COR','CP','CPAY','CPNG','CPRT','CR','CRBG','CRDO','CRH','CRRFY',
    'CRS','CSGP','CSL','CTAS','CTRA','CTVA','CUK','CVE','CW','CX',
    'D','DANOY','DASH','DASTY','DAY','DB','DBOEY','DBSDY','DCI','DEO',
    'DGX','DHI','DHLGY','DIDIY','DINO','DKILY','DKNG','DKS','DLAKY','DOC',
    'DRPRY','DSNKY','DT','DTEGY','DTM','DY','E','EADSY','EBKDY','EC',
    'EFX','EG','EGP','EL','ELAN','ELP','ELS','ELV','EMA','EMBJ',
    'EME','ENB','ENGIY','ENLAY','ENTG','EQH','EQNR','EQT','EQX','ERIC',
    'ERIE','ESLOY','ESLT','ESS','ET','EVR','EVRG','EVVTY','EWBC','EXAS',
    'EXE','EXPGY','EXR','F','FANUY','FCNCA','FER','FERG','FHN','FICO',
    'FITB','FIVE','FIX','FLEX','FLS','FLUT','FMS','FMX','FN','FNF',
    'FNV','FQVLF','FRCOY','FRFHF','FTAI','FTI','FTS','FUJHY','FUTU','FWONA',
    'FWONK','GAP','GEHC','GFI','GFS','GGG','GH','GIB','GIL','GIS',
    'GL','GLNCY','GLPI','GLW','GM','GMAB','GMED','GNRC','GPC','GRAB',
    'GRMN','GVDNY','GWRE','HBAN','HCMLY','HDB','HEI','HEINY','HENOY','HIG',
    'HL','HLDCY','HLI','HLN','HMC','HMY','HNHPF','HRL','HST','HSY',
    'HTHIY','HTHT','HUBB','IAG','IBDRY','IBDSF','IBKR','IBN','ICAGY','ICLR',
    'IDEXY','IEX','IFF','IFNNY','IMBBY','IMO','IMPUY','INFY','ING','INSM',
    'IOT','IQV','IREN','IRM','ISNPY','ITT','ITUB','IVPAF','IX','J',
    'JAPAY','JBL','JD','JEF','KB','KBCSY','KDP','KEP','KEY','KGC',
    'KHC','KHNGY','KKR','KLBAY','KMB','KMTUY','KOF','KR','KRYAY','KSPI',
    'KT','KTOS','KUASF','KVUE','KYOCY','LAMR','LDOS','LECO','LEN','LI',
    'LITE','LNT','LNVGY','LOGI','LPLA','LSCC','LTM','LVS','LYG','LYSDY',
    'LZAGY','MAA','MAKSY','MBGAF','MBGYY','MCHP','MCK','MDGL','MDLZ','MEDP',
    'MFC','MFG','MGA','MITSY','MKC','MKKGY','MKL','MLI','MLM','MMC',
    'MNST','MO','MOD','MONRY','MP','MPLX','MPWR','MSI','MSTR','MT',
    'MTB','MTUAY','MTZ','MURGY','NBIS','NDSN','NGG','NI','NIO','NNGRY',
    'NOK','NONOF','NRDBY','NRG','NTES','NTNX','NTOIY','NTR','NTRA','NTRS',
    'NU','NVMI','NVR','NVT','NWG','NXT','OC','ODFL','OHI','ONC',
    'ONON','ORI','OSK','OVV','OWL','PAA','PAAS','PAC','PAG','PAYX',
    'PBA','PBR','PDD','PEG','PEN','PFG','PFGC','PHM','PKX','PNR',
    'PNW','POAHY','PPC','PPRUY','PR','PRDSY','PRNDY','PROSY','PSA','PSKY',
    'PUK','PWR','QXO','RACE','RBA','RBC','RBGLY','RCI','RDDT','RDY',
    'RELX','REPYY','RF','RGA','RGLD','RIO','RIVN','RJF','RKLB','RKT',
    'RMBS','RMD','RNA','RNMBY','RNR','ROIV','ROL','ROP','RPM','RPRX',
    'RRX','RSG','RTO','RVMD','RVTY','RWEOY','RYAAY','RYCEY','SAFRY','SAIA',
    'SAN','SATS','SBGSY','SBS','SBSW','SCBFY','SCCO','SCGLY','SCI','SDVKY',
    'SE','SF','SFTBY','SGI','SHG','SITM','SJM','SKM','SLF','SMFG',
    'SMMNY','SMMT','SMNEY','SN','SNA','SNN','SNPS','SNX','SOLV','SPXC',
    'SQM','SSB','SSEZY','SSNC','SSUMY','STLA','STM','STRL','STT','STZ',
    'SU','SUI','SUZ','SVNLY','SW','SXYAY','SYF','SYIEY','SYM','SYY',
    'TAK','TAP','TCOM','TD','TDY','TECK','TEF','TEL','TEVA','TIGO',
    'TIMB','TKO','TLK','TLN','TME','TOL','TPG','TPL','TRI','TRMB',
    'TRMLF','TRP','TRU','TS','TSCDY','TSCO','TSEM','TSN','TTDKY','TTNDY',
    'TU','TW','TYL','UBER','UBS','UHS','UI','UL','ULS','UMBF',
    'UMC','UNCRY','UNM','UPMMY','URI','USFD','UTHR','VALE','VCISY','VEOEY',
    'VICI','VIK','VIV','VLTO','VLVLY','VMC','VNOM','VOD','VONOY','VRSK',
    'VRSN','VRT','VST','VTRS','VWAGY','VWAPY','WAB','WAL','WBS','WCC',
    'WEGZY','WES','WIT','WLK','WM','WMG','WMMVY','WPC','WPM','WRB',
    'WSO','WST','WTFC','WTKWY','WTRG','WTS','WTW','WWD','WY','WYNN',
    'XEL','XIACY','XPEV','XYL','XYZ','YARIY','YMM','YPF','YUMC','Z',
    'ZG','ZTO','ZTS','ZURVY',
  ],
  MID: [
    'WIX','PEGA','DVA','ALB','ESTC','NYT','ALGN','BROS','APA','PCTY',
    'PLNT','PATH','AA','MTCH','EPAM','AN','LAD','GTLB','NNN','SIRI',
    'CAVA','VNO','AAL','EMN','WING','CFLT','ETSY','MKTX','EAT','WH',
    'CLF','S','URBN','VFC','KMX','FROG','MSGS','MAT','BILL','TFX',
    'UPST','PCVX','NOV','QLYS','BOX','ENPH','CE','CROX','SLG','SRRK',
    'FMC','RUN','SHAK','AAP','PVH','RGTI','TENB','NVST','MGNI','ANF',
    'BL','RH','DOCN','RARE','QUBT','AEO','WU','RNG','CAKE','AI',
    'CPRI','APPN','ARWR','NWL','SEDG','YELP','AAOI','AAON','AB','ABCB',
    'ABG','ABM','ABVX','ACA','ACAD','ACDVF','ACHR','ACI','ACIW','ACLS',
    'ACLX','ACMR','ACT','AD','ADC','ADMA','ADPT','ADT','AEIS','AG',
    'AGCO','AGRO','AGX','AGYS','AIIXY','AIR','AKR','AL','ALG','ALGM',
    'ALK','ALSN','ALV','AM','AMBA','AMBP','AMG','AMR','AMRX','AMTM',
    'APAM','APGE','APLD','APLE','APLS','APPF','AQN','ARCB','ARKAY','ARLP',
    'AROC','ARQT','ARW','ASAN','ASB','ASGN','ASO','ATAT','ATGE','ATKR',
    'ATMU','ATR','ATRO','ATZAF','AUB','AUGO','AUR','AVA','AVAL','AVDL',
    'AVPT','AVT','AWI','AWR','AX','AXSM','AXTA','AYI','AZZ','BANC',
    'BATRK','BB','BBAR','BBU','BBWI','BC','BCC','BCO','BCPC','BEAM',
    'BELFA','BELFB','BEP','BEPC','BFAM','BFH','BHC','BHF','BIPC','BIRK',
    'BKE','BKH','BKU','BKV','BLCO','BLKB','BMA','BMI','BMNR','BNL',
    'BOH','BOKF','BOOT','BOSSY','BPOP','BRBR','BRC','BRKR','BRSL','BRX',
    'BSM','BTDR','BTE','BTG','BTU','BULL','BURBY','BXSL','BYD','BZ',
    'CAAP','CADE','CAE','CAG','CALM','CALX','CAMT','CAR','CARG','CART',
    'CASH','CATY','CBSH','CBT','CBU','CBZ','CC','CCC','CCOEY','CCS',
    'CCU','CDLR','CDP','CDTX','CECO','CELC','CENT','CENX','CEPU','CESDF',
    'CFR','CGAU','CGNX','CGON','CHDN','CHEF','CHH','CHRD','CIFR','CIVI',
    'CLBT','CLMT','CLSK','CMBT','CMC','CMPO','CNK','CNR','CNS','CNX',
    'CNXC','COCO','COGT','COLD','COLM','COMM','COMP','CORT','CORZ','COTY',
    'CPA','CPB','CPRX','CRC','CRGY','CRK','CRL','CRNX','CRSP','CRUS',
    'CSTM','CSW','CTRE','CUBE','CUBI','CUZ','CVBF','CVCO','CVI','CVLT',
    'CWAN','CWEN','CWK','CWST','CWT','CXT','CYTK','CZR','DAN','DAR',
    'DAVE','DBD','DBRG','DBX','DDS','DHT','DIOD','DK','DKL','DLB',
    'DLO','DNLI','DNN','DNNGY','DOCS','DORM','DOX','DRD','DRS','DRVN',
    'DSGX','DXC','DXPE','DYN','EBC','ECG','EDNMY','EDU','EGO','ELF',
    'ENIC','ENS','ENVA','EOSE','EPAC','EPR','EPRT','ERAS','ERO','ESAB',
    'ESI','ESNT','EXK','EXLS','EXP','EXTR','EYE','FAF','FBIN','FBK',
    'FBP','FCFS','FCN','FCPT','FELE','FFBC','FFIN','FG','FHB','FHI',
    'FIBK','FIHL','FIZZ','FLG','FLNC','FLO','FLR','FMCC','FNB','FND',
    'FNMA','FOLD','FORM','FOUR','FR','FRME','FRO','FRPT','FRSH','FRT',
    'FSK','FSM','FSS','FTDR','FUL','FULT','FUPBY','G','GATX','GBCI',
    'GBDC','GDS','GEL','GEO','GFF','GGAL','GGB','GHC','GLBE','GLNG',
    'GLOB','GLXY','GNL','GNTX','GOLF','GPCR','GPI','GPK','GPOR','GRAL',
    'GRBK','GRFS','GSAT','GT','GTES','GTLS','GTM','GTX','GVA','GXO',
    'HAE','HAFN','HALO','HASI','HAYW','HBM','HCC','HCI','HESM','HG',
    'HGTY','HGV','HHH','HI','HIMS','HIW','HNI','HOG','HOMB','HP',
    'HQY','HR','HRB','HRMY','HSAI','HSIC','HTGC','HTH','HUN','HURN',
    'HUT','HWC','HXL','HYMC','IBP','IBRX','ICL','IDA','IDCC','IDYA',
    'IEP','IESC','IFS','IHS','IMCDY','IMNM','IMVT','INDB','INGM','INGR',
    'INSW','INTR','IOSP','IPAR','IRDM','IRON','IRT','ITGR','ITRI','IVT',
    'JAZZ','JBTM','JHG','JOBY','JOYY','JRONY','JXN','KAI','KALU','KBH',
    'KBR','KC','KD','KEX','KFY','KGS','KLIC','KMT','KN','KNF',
    'KNSA','KNSL','KNTK','KNX','KRC','KRG','KRYS','KTB','KVYO','KWR',
    'KYIV','KYMR','LASR','LAUR','LB','LBRT','LCID','LEA','LEU','LEVI',
    'LGND','LIF','LINE','LION','LIVN','LKQ','LMND','LNC','LNTH','LOAR',
    'LOPE','LPL','LPX','LQDA','LRN','LTH','LUMN','LUNR','LW','LXP',
    'LYFT','M','MAC','MAIN','MANU','MARA','MATX','MBLY','MC','MCHB',
    'MCY','MESO','MGEE','MGM','MGY','MHK','MHO','MIDD','MIR','MMS',
    'MMSI','MMYT','MNSO','MODG','MORN','MOS','MPW','MRCY','MRP','MRUS',
    'MRX','MSA','MSGE','MSM','MTDR','MTG','MTH','MTN','MTRN','MUR',
    'MUSA','MWA','MYRG','MZTI','NAMS','NATL','NCNO','NE','NEOG','NESR',
    'NFG','NG','NGD','NHI','NIC','NICE','NJR','NMIH','NMRK','NOG',
    'NOVT','NPO','NSA','NSANY','NUVL','NWE','NWN','NXST','OBDC','OGN',
    'OGS','OI','OKLO','OLED','OLLI','OLN','OMAB','OMF','ONB','ONDS',
    'ONTO','OPEN','OR','ORLA','OS','OSCR','OSIS','OTEX','OTTR','OZK',
    'PAGP','PAGS','PAM','PARR','PATK','PAX','PAYO','PB','PBF','PCH',
    'PCOR','PECO','PEYUF','PFS','PHI','PHIN','PII','PIPR','PK','PL',
    'PLAB','PLMR','PNFP','PONY','POR','POST','POWI','POWL','PPTA','PRAX',
    'PRDO','PRI','PRIM','PRM','PRMB','PRVA','PSMT','PSN','PSO','PTCT',
    'PTEN','PTGX','PUMSY','QBTS','QRVO','QS','QTWO','R','RBRK','RCUS',
    'RDN','REAL','RELY','RERE','REVG','REXR','REYN','REZI','RGEN','RHI',
    'RHP','RIG','RIOT','RLI','RLX','RNST','ROAD','RRC','RRR','RSI',
    'RUM','RUSHA','RXO','RYN','RYTM','SAH','SAIC','SAM','SANM','SARO',
    'SBLK','SBRA','SDRL','SEE','SEI','SEZL','SFM','SFNC','SGHC','SHOO',
    'SIG','SII','SIMO','SITE','SKT','SKY','SKYW','SLAB','SLGN','SLM',
    'SLNO','SLVM','SLVYY','SM','SMG','SMR','SMTC','SOBO','SON','SONO',
    'SOUN','SPHR','SPNT','SPSC','SR','SRAD','SSD','SSL','SSRM','ST',
    'STAG','STNE','STNG','SUBCY','SUN','SVM','SWKS','SXI','SYNA','TAC',
    'TAL','TALO','TARS','TBBB','TBBK','TCBI','TDC','TDS','TDW','TEM',
    'TEO','TERN','TEX','TFII','TFPM','TFSL','TGB','TGLS','TGS','TGTX',
    'THG','THO','TKC','TKR','TLPFY','TMC','TMDX','TMHC','TNET','TNK',
    'TNL','TPB','TPC','TPH','TREX','TRMD','TRN','TRNO','TTAN','TTC',
    'TTMI','TVTX','TWST','TX','UAA','UBSI','UEC','UFPI','UGI','UHAL',
    'UNF','UNFI','UPWK','USAC','USAR','USLM','UUUU','UWMC','VAL','VCTR',
    'VEON','VERA','VERX','VFS','VIAV','VICR','VIPS','VIRT','VIST','VKTX',
    'VLY','VMI','VNET','VNT','VOYA','VRDN','VRNS','VRRM','VSAT','VSCO',
    'VSEC','VSH','VVV','VVX','WB','WDFC','WERN','WEX','WFG','WFRD',
    'WGS','WHD','WHR','WK','WOR','WPP','WRBY','WRD','WS','WSBC',
    'WSC','WT','WULF','WVE','XMTR','XP','XRAY','YETI','YOU','ZETA',
    'ZGN','ZIM','ZION','ZK','ZWS',
  ],
  SMALL: [
    'COUR','SRPT','TRIP','JBLU','LC','PLUG','NVAX','FSLY','ARRY','WOOF',
    'PUBM','AAT','AAVVF','ABAT','ABCL','ABL','ACCO','ACDC','ACEL','ACHC',
    'ACIC','ACVA','ADNT','ADTN','ADUR','AEHR','AESI','AEVA','AFYA','AGIO',
    'AGM','AHH','AIN','AIOT','AIP','AKBA','ALEX','ALGT','ALLO','ALLT',
    'ALNT','ALT','ALVO','AMC','AMLX','AMPH','AMPL','AMPX','AMRC','AMSC',
    'AMWD','ANAB','ANGI','ANGO','ANIP','ANNX','ANRO','AOSL','API','APPS',
    'AQST','ARCO','ARDX','ARHS','ARKO','ARLO','AROW','ARREF','ARTNA','ARVN',
    'ASC','ASIX','ASLE','ASM','ASPI','ASTL','ATAI','ATEN','ATHM','ATLC',
    'ATXS','AUPH','AURA','AUTL','AVAH','AVO','AVXL','AXGN','AXTI','AZTA',
    'BAK','BALY','BAND','BBAI','BBBY','BBCP','BBDC','BBOT','BBSI','BBW',
    'BCAL','BCAX','BCRX','BCSF','BCYC','BDN','BETR','BEVFF','BFLY','BFS',
    'BHB','BHVN','BITF','BJRI','BKSY','BLBD','BLDP','BLFS','BLMN','BLND',
    'BLX','BMBL','BOC','BORR','BOW','BRZE','BSVN','BTBT','BTQ','BV',
    'BVS','BW','BWAY','BWB','BWFG','BWIN','BWMN','BWMX','BY','BYND',
    'BZH','CAL','CAPL','CAPR','CARS','CASS','CBL','CBRL','CCAP','CCBG',
    'CCEC','CCO','CCOI','CDRE','CDZI','CERS','CERT','CEVA','CFFN','CGBD',
    'CGC','CGEM','CGNT','CHCO','CHCT','CINT','CION','CIVB','CLDT','CLDX',
    'CLFD','CLMB','CLOV','CLPT','CLVT','CMCL','CMCO','CMP','CMPS','CMRE',
    'CNMD','CNOB','CODI','COHU','COLL','CPAC','CPS','CRI','CRLBF','CRMD',
    'CRNC','CRON','CRSR','CRTO','CRVS','CSAN','CSIQ','CSR','CSV','CSWC',
    'CTBI','CTGO','CTKB','CTLP','CTMX','CTO','CTRN','CURLF','CVAC','CVGW',
    'CVLG','CWH','CXM','CXW','CYBN','CYD','CYRX','CZNC','DAC','DAKT',
    'DAO','DAWN','DBI','DBVT','DCBO','DCO','DCOM','DCTH','DEA','DEC',
    'DEI','DENN','DFH','DGICA','DGII','DIN','DNA','DNOW','DNUT','DOLE',
    'DQ','DRH','DRTS','DSP','DV','DVAX','EAF','EB','EBF','EBS',
    'ECO','EEX','EGBN','EGY','EH','EIG','ELA','ELVA','ELVN','EMBC',
    'ENGN','ENOV','ENR','ENVX','EPC','EQBK','ERII','ESEA','ESPR','ESRT',
    'ETD','ETON','EU','EVCM','EVER','EVEX','EVGO','EVLV','EVO','EVTL',
    'EXPI','EYPT','EZPW','FCEL','FCF','FDMT','FDP','FDUS','FEIM','FIGS',
    'FINV','FISI','FIVN','FLGT','FLNG','FLYW','FMAO','FMNB','FOR','FOXF',
    'FPI','FRGE','FSUN','FTK','FTRE','FUBO','FUFU','FUN','FVR','FVRR',
    'FWRG','GAIN','GAU','GBX','GCMG','GCT','GDEN','GDOT','GDRX','GDYN',
    'GENI','GERN','GETY','GEVO','GFR','GHM','GIII','GILT','GLAD','GLASF',
    'GLDD','GLP','GLUE','GMRE','GNE','GO','GOGO','GOOD','GOOS','GOTU',
    'GPRE','GPRK','GRND','GRNT','GROY','GRPN','GSBD','GSL','GSM','GTBIF',
    'GTN','GTY','HBNC','HBT','HCKT','HCSG','HDSN','HELE','HIMX','HIVE',
    'HLF','HLX','HMN','HNRG','HOPE','HOUS','HOV','HPK','HPP','HROW',
    'HRTG','HTLD','HTO','HTZ','HUYA','HYLN','IBEX','IBTA','ICFI','ICHR',
    'IDR','IDT','IIIN','IIIV','IIPR','ILPT','IMAX','IMCR','IMTX','INBX',
    'INDI','INMD','INN','INOD','INSP','INTA','INVX','IOVA','IPI','IQ',
    'IRS','IRWD','ITRG','ITRN','JACK','JAGGF','JANX','JBI','JBSS','JJSF',
    'JKS','JMIA','JRVR','KALV','KARO','KDK','KE','KELYA','KFRC','KLC',
    'KNOP','KOD','KOP','KOPN','KOS','KRNT','KRNY','KROS','KRP','KRT',
    'KRUS','KSS','KURA','KW','KYTX','LAC','LAND','LAR','LCTX','LE',
    'LEG','LEGH','LEGN','LENZ','LGIH','LINC','LKNCY','LMB','LNN','LNXSY',
    'LOB','LOCO','LOMA','LPG','LPTH','LQDT','LSPD','LTC','LUCK','LUXE',
    'LWAY','LX','LXEO','LXRX','LZ','LZB','MAMA','MAN','MATW','MAX',
    'MBC','MBIN','MBUU','MBX','MCB','MCFT','MCRI','MCS','MCW','MDRX',
    'MDXG','MEC','MEG','METC','MFIC','MG','MGPI','MGTX','MITK','MLAB',
    'MLCO','MLKN','MLR','MLTX','MLYS','MMI','MNKD','MNMD','MNPR','MNR',
    'MNRO','MOFG','MOMO','MOV','MRTN','MSDL','MSEX','MTLS','MTW','MUX',
    'MVST','MXL','MYE','MYGN','NAGE','NAK','NAT','NATR','NB','NBHC',
    'NBN','NBP','NBR','NBTX','NCDL','NECB','NEWP','NEWT','NEXA','NEXT',
    'NFE','NGL','NGS','NGVC','NKTR','NMFC','NMM','NNE','NOA','NOMD',
    'NPKI','NRDS','NRGV','NRIM','NRIX','NSSC','NTCT','NTLA','NTST','NUTX',
    'NUVB','NVCR','NVGS','NVRI','NVTS','NWBI','NX','NXDR','NXRT','NYAX',
    'OBE','OCGN','OCSL','OCUL','ODD','OFG','OIS','OLMA','OLP','OLPX',
    'OMER','ONIT','OOMA','OPFI','OPK','OPRA','OPTU','ORGO','ORN','OSPN',
    'OTLY','OUST','OXM','PACK','PAR','PBAM','PBI','PCRX','PCT','PD',
    'PDFS','PDLB','PDM','PDS','PEB','PEBO','PENG','PENN','PERI','PFBC',
    'PFLT','PGEN','PGNY','PGRE','PGY','PHAT','PHVS','PKOH','PKST','PLAY',
    'PLOW','PLPC','PLTK','PLYM','PNNT','POET','PRAA','PRCH','PRCT','PRG',
    'PRGO','PRGS','PRKS','PRLB','PRME','PROK','PSEC','PSFE','PSIX','PSNL',
    'PSNY','PSTL','PTLO','PTON','PUMP','PVLA','PZZA','QDEL','QFIN','QNST',
    'QURE','RAMP','RAPT','RBB','RCAT','RDW','REAX','REPL','REPX','RGNX',
    'RGR','RIGL','RLAY','RLJ','RNW','ROCK','ROOT','RPD','RR','RSKD',
    'RVLV','RWAY','RXRX','RXST','RYI','RZLV','SABR','SAFE','SANA','SAR',
    'SB','SBC','SBET','SBGI','SBH','SBSI','SCHL','SCL','SCM','SCVL',
    'SD','SDGR','SEMR','SEPN','SERV','SES','SFIX','SFL','SFST','SG',
    'SGML','SHBI','SHLS','SHO','SILA','SKWD','SKYH','SKYT','SLDP','SLI',
    'SLRC','SLSR','SMA','SMP','SMPL','SMWB','SNCY','SNDL','SNDX','SOC',
    'SOHU','SPB','SPH','SPRY','SPT','SRTA','SSP','SSTK','SSYS','STAA',
    'STKL','STOK','STRA','STRT','SUPV','SVC','SVRA','SVV','SWBI','SWIM',
    'TALK','TASK','TATT','TBLA','TCBX','TCNNF','TCPC','TDAY','TDOC','TDUP',
    'TE','TECX','TEN','TFIN','THFF','THR','THRM','THS','TIC','TIGR',
    'TITN','TLRY','TLS','TMP','TMQ','TNC','TNGX','TRDA','TREE','TRIN',
    'TRNS','TRS','TRVI','TSHA','TSLX','TTI','TUYA','TV','TWFG','TWI',
    'UAMY','UBSFY','UCTT','UDMY','UFCS','ULCC','UMAC','UMH','UNIT','UNTY',
    'UPB','UPBD','URG','URGN','UROY','UTI','UTL','UTZ','UVE','VAC',
    'VECO','VET','VFF','VINP','VITL','VLRS','VNDA','VPG','VRE','VSTM',
    'VSTS','VTEX','VTOL','VTS','VTYX','VZLA','WASH','WBTN','WEAV','WEN',
    'WEST','WGO','WINA','WLDN','WLFC','WLY','WRDLY','WRLD','WSR','WTTR',
    'WWW','XERS','XHR','XIFR','XNCR','XOMA','XPEL','XPRO','YEXT','YORW',
    'YSG','ZBIO','ZD','ZLAB','ZUMZ','ZYME',
  ],
  MICRO: [
    'XPOF','ACB','ARQQ','BKKT','BRCC','BRT','BYRN','CADL','CAN','CLW',
    'CMRC','CNDT','DAVA','DEFT','DOMO','DVLT','ELME','ENTA','EOLS','GALT',
    'GRRR','HNST','IMRX','IVVD','LAW','LFCR','MREO','NOAH','NPWR','OSG',
    'OWLT','PEPG','RMNI','SLP','STRW','VERI','VOR','VOXR','WDH','XFOR',
    'XRX','ZEPP',
  ],
}

/**
 * Segment bazli veya tum sembolleri dondur
 */
export function getSymbols(segment: Segment): string[] {
  if (segment === 'ALL') {
    return [
      ...SEGMENTS.MEGA,
      ...SEGMENTS.LARGE,
      ...SEGMENTS.MID,
      ...SEGMENTS.SMALL,
      ...SEGMENTS.MICRO,
    ]
  }
  return SEGMENTS[segment] || []
}

/**
 * Bir sembolun segmentini bul
 */
export function getSegment(symbol: string): string {
  for (const [seg, symbols] of Object.entries(SEGMENTS)) {
    if (symbols.includes(symbol)) return seg
  }
  return 'UNKNOWN'
}

/**
 * Toplam hisse sayisi
 */
export function getTotalSymbolCount(): number {
  return Object.values(SEGMENTS).reduce((sum, arr) => sum + arr.length, 0)
}

/**
 * Segment istatistikleri
 */
export function getSegmentStats(): Record<string, number> {
  const stats: Record<string, number> = {}
  for (const [seg, symbols] of Object.entries(SEGMENTS)) {
    stats[seg] = symbols.length
  }
  stats['ALL'] = getTotalSymbolCount()
  return stats
}
